[tool.pytest.ini_options]
pythonpath = "."
addopts = "--doctest-modules"

[tool.isort]
profile = "black"
line_length = 79

[tool.taskipy.tasks]
check = "black --check --diff . && isort --check --diff ."
correct = "black . && isort ."
docs = "mkdocs serve"
test = "pytest -s -x  -vv"
post_test = "coverage html"
