# Generated by Django 5.0.3 on 2024-05-06 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("species", models.CharField(max_length=255)),
                ("breed", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("color", models.CharField(max_length=255)),
                ("sex", models.CharField(max_length=255)),
                ("size", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("history", models.TextField()),
                ("observations", models.TextField()),
                ("photos", models.CharField(max_length=255)),
                ("adopted", models.BooleanField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="userprofile.profile",
                    ),
                ),
            ],
        ),
    ]
