# Generated by Django 5.0.6 on 2024-06-04 18:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryPet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.TextField(blank=True, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImagesPets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_pet_profile",
                    models.ImageField(upload_to="pets/profile/%Y/%m/"),
                ),
                (
                    "image_pet_datail1",
                    models.ImageField(upload_to="pets/photos/%Y/%m/"),
                ),
                (
                    "image_pet_datail2",
                    models.ImageField(upload_to="pets/photos/%Y/%m/"),
                ),
                (
                    "image_pet_datail3",
                    models.ImageField(upload_to="pets/photos/%Y/%m/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("castreated", models.BooleanField(blank=True, null=True)),
                ("vaccines", models.BooleanField(blank=True, null=True)),
                ("vaccine_description", models.TextField(blank=True, null=True)),
                ("dewormed", models.BooleanField(blank=True, null=True)),
                ("dewormer_description", models.TextField(blank=True, null=True)),
                ("medical_history", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "species",
                    models.CharField(
                        choices=[("DOG", "Dog"), ("CAT", "Cat")], max_length=20
                    ),
                ),
                ("breed", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("color", models.CharField(max_length=255)),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Macho"), ("Female", "Femea")], max_length=20
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("SMALL", "Pequeno"),
                            ("MEDIUM", "Medio"),
                            ("Large", "Grande"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight", models.IntegerField()),
                ("heigth", models.IntegerField()),
                ("adopted", models.BooleanField(default=False)),
                ("favorited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]


# Generated by Django 5.0.6 on 2024-06-04 18:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryPet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.TextField(blank=True, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImagesPets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_pet_profile",
                    models.ImageField(upload_to="pets/profile/%Y/%m/"),
                ),
                (
                    "image_pet_datail1",
                    models.ImageField(upload_to="pets/photos/%Y/%m/"),
                ),
                (
                    "image_pet_datail2",
                    models.ImageField(upload_to="pets/photos/%Y/%m/"),
                ),
                (
                    "image_pet_datail3",
                    models.ImageField(upload_to="pets/photos/%Y/%m/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("castreated", models.BooleanField(blank=True, null=True)),
                ("vaccines", models.BooleanField(blank=True, null=True)),
                ("vaccine_description", models.TextField(blank=True, null=True)),
                ("dewormed", models.BooleanField(blank=True, null=True)),
                ("dewormer_description", models.TextField(blank=True, null=True)),
                ("medical_history", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "species",
                    models.CharField(
                        choices=[("DOG", "Dog"), ("CAT", "Cat")], max_length=20
                    ),
                ),
                ("breed", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("color", models.CharField(max_length=255)),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Macho"), ("Female", "Femea")], max_length=20
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("SMALL", "Pequeno"),
                            ("MEDIUM", "Medio"),
                            ("Large", "Grande"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight", models.IntegerField()),
                ("heigth", models.IntegerField()),
                ("adopted", models.BooleanField(default=False)),
                ("favorited", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
