# Generated by Django 5.0.3 on 2024-05-06 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="image_profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="pets/profile/imagesPets/%Y/%m/"
            ),
        ),
        migrations.CreateModel(
            name="ImagesPets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_pets",
                    models.ImageField(
                        blank=True, null=True, upload_to="pets/photos/imagesPets/%Y/%m/"
                    ),
                ),
                (
                    "id_pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ImagesPets",
                        to="pet.pet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("castreated", models.BooleanField()),
                ("vaccines", models.BooleanField()),
                ("vaccine_description", models.TextField()),
                ("dewormed", models.BooleanField()),
                ("dewormer_description", models.TextField()),
                ("medical_history", models.TextField()),
                (
                    "id_pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="pet.pet",
                    ),
                ),
            ],
        ),
    ]
