# Generated by Django 5.0.6 on 2024-05-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="sex",
            field=models.CharField(
                choices=[("Male", "Macho"), ("Female", "Femea")], max_length=20
            ),
        ),
    ]
