# Generated by Django 5.0.6 on 2024-05-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0002_alter_pet_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="adopted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="observations",
            field=models.TextField(blank=True, null=True),
        ),
    ]
