# Generated by Django 5.0.6 on 2024-06-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="favorited",
            field=models.BooleanField(default=False),
        ),
    ]
