# Generated by Django 5.0.6 on 2024-05-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pets/photos/imagesPets/%Y/%m/")),
            ],
        ),
        migrations.AlterField(
            model_name="imagespets",
            name="id_pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images_pets",
                to="pet.pet",
            ),
        ),
        migrations.RemoveField(
            model_name="imagespets",
            name="image_pets",
        ),
        migrations.AddField(
            model_name="imagespets",
            name="image_pets",
            field=models.ManyToManyField(
                blank=True, related_name="pets_images", to="pet.image"
            ),
        ),
    ]
