# Generated by Django 5.0.6 on 2024-06-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0003_pet_adoption_adoptionpets_favoritedpet"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerImagens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner_image1", models.ImageField(upload_to="banner/imagens/%Y/%m/")),
                ("banner_image2", models.ImageField(upload_to="banner/imagens/%Y/%m/")),
                ("banner_image3", models.ImageField(upload_to="banner/imagens/%Y/%m/")),
            ],
        ),
    ]
