# Generated by Django 5.0.3 on 2024-05-06 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0004_alter_pet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
