# Generated by Django 5.0.3 on 2024-05-06 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0008_alter_pet_id"),
        ("userprofile", "0006_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="userprofile.profile",
            ),
        ),
    ]
