# Generated by Django 5.0.3 on 2024-05-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0010_alter_pet_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="photos",
        ),
    ]
