# Generated by Django 5.0.3 on 2024-05-10 18:31

import django.db.models.deletion
import shortuuid.django_fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0006_alter_profile_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="password",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="role",
        ),
        migrations.AddField(
            model_name="profile",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("in-active", "In-active"),
                ],
                default="in-active",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="red_code",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh1234567890",
                length=10,
                max_length=20,
                prefix="",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
