# Generated by Django 5.0.3 on 2024-05-16 17:47

import django.db.models.deletion
import utils.idrandom
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pet", "0001_initial"),
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adoption",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        default=utils.idrandom.random_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=255)),
                (
                    "adopter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adopted_pets",
                        to="userprofile.profile",
                    ),
                ),
                (
                    "pet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="pet.pet"
                    ),
                ),
            ],
        ),
    ]
