# Generated by Django 5.0.3 on 2024-05-06 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoption", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoption",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
