# Generated by Django 5.0.6 on 2024-06-04 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adoption", "0001_initial"),
        ("pet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adoption",
            name="adopter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adopted_pets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adoption",
            name="pet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="pet.pet"
            ),
        ),
    ]
