# Generated by Django 5.0.6 on 2024-06-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adoption", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Adoption",
        ),
    ]
