# Generated by Django 5.0.3 on 2024-05-06 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoption", "0004_alter_adoption_id"),
        ("userprofile", "0006_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoption",
            name="adopter",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adopted_pets",
                to="userprofile.profile",
            ),
        ),
    ]
