# Generated by Django 5.0.3 on 2024-05-06 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoption", "0005_alter_adoption_adopter"),
        ("pet", "0010_alter_pet_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoption",
            name="pet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="pet.pet"
            ),
        ),
    ]
