# Generated by Django 5.0.3 on 2024-05-06 19:07

import django.db.models.deletion
import utils.idrandom
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adoption", "0006_alter_adoption_pet"),
        ("pet", "0010_alter_pet_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adoption",
            name="id",
            field=models.UUIDField(
                default=utils.idrandom.random_id,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="adoption",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pet.pet"
            ),
        ),
    ]
