# Generated by Django 5.0.6 on 2024-05-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image_profile",
            new_name="image_user_profile",
        ),
    ]
