# Generated by Django 5.0.6 on 2024-05-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0002_rename_image_profile_user_image_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image_user_profile",
            field=models.ImageField(upload_to="user/profile/%Y/%m/"),
        ),
    ]
