# Generated by Django 5.0.6 on 2024-06-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0002_remove_user_usernamefull_alter_user_username"),
    ]

    operations = []
