# Generated by Django 5.0.6 on 2024-05-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0003_alter_user_image_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image_user_profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="user/profile/%Y/%m/"
            ),
        ),
    ]
