# Generated by Django 5.0.6 on 2024-05-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adoption", "0002_alter_adoption_adopter"),
        ("pet", "0004_alter_pet_owner"),
        ("userauth", "0004_alter_user_image_user_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
